### PR TITLE
fix README typo "will"  -> "we"

### PR DESCRIPTION
**Pull request by hoijui**

### CODE REVIEW

**Comment by lislis** [comment]
Hey @hoijui thanks for fixing this!

**Comment by hoijui** [comment]
a pleasure! :-)
thanks for making stuff open source!
btw, are the sources for the "Coaches Training Slides" online aswell?

**Comment by lislis** [comment]
Hi @hoijui, there are a bit hidden (I had to ask to find them, too)
https://github.com/clojurebridge-berlin/clojurebridge-berlin.github.io/blob/master/coaches_training.deck.html

**Comment by hoijui** [comment]
cool, thanks! :-)
i proposed two small changes there too

**Pull request merged**
